title: [MVC Through Scripting Languages]
description: [Welcome to the class]
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - intro_to_mvctsl.md
  - README.md
  - why_python.md
  - intro_to_python.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: jekyll-theme-cayman
